# Generated by Django 3.2 on 2021-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='executor_id',
            new_name='executor',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='status_id',
            new_name='status',
        ),
    ]
