# Generated by Django 3.2 on 2021-04-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(error_messages={'unique': 'Задача с таким названием уже существует!'}, help_text='HelpTaskFieldText', max_length=150, unique=True, verbose_name='TasksName'),
        ),
    ]
