# Generated by Django 3.2 on 2021-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='StatusName'),
        ),
    ]
