# Generated by Django 3.2 on 2021-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(db_index=True, error_messages={'blank': 'ThisFieldCannotBeBlank', 'unique': 'StatusWithThisNameAlreadyExist'}, help_text='HelpStatusFieldText', max_length=100, unique=True, verbose_name='StatusName'),
        ),
    ]
